"""
Django settings for Pradhan_Chemistry_Classes project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = BASE_DIR / 'templates'




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-by0sbe^rzo)ys-p4pz4%-a(0tsf-*!8vt%(d*4n(8$x$)9yv)d",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]
render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if not render_host:
    render_url = os.getenv("RENDER_EXTERNAL_URL", "").strip()
    if render_url:
        parsed_url = urlparse(render_url)
        if parsed_url.hostname:
            render_host = parsed_url.hostname
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Pradhan_Chemistry_Classes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, BASE_DIR / 'admissions' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Pradhan_Chemistry_Classes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url

    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=False)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if render_host and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [f"https://{render_host}"]

PAYMENT_UPI_ID = os.getenv("PAYMENT_UPI_ID", "")
PAYMENT_RECEIVER_NAME = os.getenv("PAYMENT_RECEIVER_NAME", "Pradhan Chemistry Classes")
PAYMENT_GATEWAY = os.getenv("PAYMENT_GATEWAY", "Razorpay")
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "")
PHONEPE_MERCHANT_ID = os.getenv("PHONEPE_MERCHANT_ID", "")
PHONEPE_SALT_KEY = os.getenv("PHONEPE_SALT_KEY", "")
PHONEPE_SALT_INDEX = os.getenv("PHONEPE_SALT_INDEX", "")
PHONEPE_BASE_URL = os.getenv("PHONEPE_BASE_URL", "https://api-preprod.phonepe.com/apis/pg-sandbox")
PHONEPE_VERIFY_CALLBACK = env_bool("PHONEPE_VERIFY_CALLBACK", default=True)

SEND_PAYMENT_NOTIFICATIONS = env_bool("SEND_PAYMENT_NOTIFICATIONS", default=True)
DEFAULT_COUNTRY_CODE = os.getenv("DEFAULT_COUNTRY_CODE", "+91")
SMS_PROVIDER = os.getenv("SMS_PROVIDER", "twilio")
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.getenv("TWILIO_FROM_NUMBER", "")
WHATSAPP_PROVIDER = os.getenv("WHATSAPP_PROVIDER", "cloud")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v19.0")

INVOICE_TITLE = os.getenv("INVOICE_TITLE", "Pradhan Chemistry Classes")
INVOICE_SUBTITLE = os.getenv("INVOICE_SUBTITLE", "Fee Receipt")
INVOICE_ADDRESS = os.getenv(
    "INVOICE_ADDRESS",
    "Veer Kunwar Singh Colony, Near Power House, Buxar, Bihar 802101 | Director: Anu Pradhan",
)
INVOICE_LOGO_PATH = os.getenv("INVOICE_LOGO_PATH", "static/invoice_logo.png")
INVOICE_SIGNATURE_PATH = os.getenv("INVOICE_SIGNATURE_PATH", "static/signature.png")
INVOICE_STAMP_PATH = os.getenv("INVOICE_STAMP_PATH", "static/stamp.png")
INVOICE_WATERMARK_TEXT = os.getenv("INVOICE_WATERMARK_TEXT", "Pradhan Chemistry Classes")
INVOICE_QR_TEMPLATE = os.getenv("INVOICE_QR_TEMPLATE", "").strip()
if not INVOICE_QR_TEMPLATE:
    if render_host:
        INVOICE_QR_TEMPLATE = f"https://{render_host}/receipt/{{admission_id}}/pdf/"
    else:
        INVOICE_QR_TEMPLATE = "http://127.0.0.1:8000/receipt/{admission_id}/pdf/"
