# Generated by Django 6.0 on 2026-02-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='date',
        ),
        migrations.AddField(
            model_name='admission',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('BSEB', 'BSEB')], default='CBSE', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='fee_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='medium',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='Hindi', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='student_class',
            field=models.CharField(choices=[('11', '11'), ('12', '12')], default='12', max_length=2),
        ),
        migrations.AddField(
            model_name='batch',
            name='student_class',
            field=models.CharField(choices=[('11', '11'), ('12', '12')], default='12', max_length=2),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='student_class',
            field=models.CharField(choices=[('11', '11'), ('12', '12')], default='12', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.batch'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='fee_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='filled_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='medium',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='medium',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='offer_fee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feeplan',
            name='original_fee',
            field=models.PositiveIntegerField(),
        ),
    ]
