# Generated by Codex on 2026-02-09

from datetime import date

from django.db import migrations


def seed_class11_feeplans(apps, schema_editor):
    FeePlan = apps.get_model("admissions", "FeePlan")
    FeePlan.objects.get_or_create(
        student_class="11",
        medium="Hindi",
        defaults={
            "original_fee": 4000,
            "offer_fee": 4000,
            "offer_end_date": date.today(),
        },
    )
    FeePlan.objects.get_or_create(
        student_class="11",
        medium="English",
        defaults={
            "original_fee": 4500,
            "offer_fee": 4500,
            "offer_end_date": date.today(),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_seed_feeplan_defaults"),
    ]

    operations = [
        migrations.RunPython(seed_class11_feeplans, migrations.RunPython.noop),
    ]
