# Generated by Django 6.0 on 2026-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_seed_feeplan_class11'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
