# Generated by Django 6.0 on 2026-02-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_admission_fee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Online', 'Online')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
    ]
