# Generated by Django 6.0 on 2026-02-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_payment_gateway_payment_order_id_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
